services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,sqs
      - DATA_DIR=/var/lib/localstack/data
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_volume:/var/lib/localstack
      - ./docker/init-scripts/setup-infra.sh:/etc/localstack/setup-localstack.sh
    entrypoint: >
      sh -c "docker-entrypoint.sh & 
      sleep 5
      echo 'LocalStack pronto! Executando script...';
      chmod +x /etc/localstack/setup-localstack.sh &&  
      /etc/localstack/setup-localstack.sh && wait"
    restart: always

  postgres:
    container_name: game-db-postgres
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: game-analytics
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /data/postgres
    volumes:
      - ./game-data/pg:/data/postgres
    networks:
      - game-network

  redis:
    container_name: game-cache-redis
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - game-network
    volumes:
      - ./game-data/redis:/data

  redis-commander:
    container_name: game-redis-gui
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081
    networks:
      - game-network
    depends_on:
      - redis

volumes:
  game-data:
  localstack_volume:

networks:
  game-network:
    driver: bridge