version: '3.8'

services:
  postgres:
    container_name: game-db-postgres
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: game-analytics
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /data/postgres
    volumes:
      - ./game-data/pg:/data/postgres

  redis:
    container_name: game-cache-redis
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - redis-network
    volumes:
      - ./game-data/redis:/data

  redis-commander:
    container_name: game-redis-gui
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081
    networks:
      - redis-network
    depends_on:
      - redis

  seq:
    container_name: game-seq-monitoring
    image: datalust/seq:latest
    restart: always
    ports:
      - "5341:80"
      - "5342:5342" # OTEL Exporter
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./game-data/seq:/data

volumes:
  game-data:

networks:
  redis-network:
    driver: bridge